// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.07/07       [395015]
Creator        : rabah
Date           : Fri Jul 22 12:37:03 2016
Host           : Darwin mba-amhis.lal.in2p3.fr 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
Dir            : /Users/rabah/Desktop/Hybrid_MVA/inFlagHits/Allev_CasesSeparation_recoveryOFF/case1
Training events: 319821
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
# Default:
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
chi2                          chi2                          chi2                          chi2                                                            'D'    [0.00779165606946,37.0541687012]
nx                            nx                            nx                            nx                                                              'D'    [4,6]
ny                            ny                            ny                            ny                                                              'D'    [4,6]
X0Back                        X0Back                        X0Back                        X0Back                                                          'D'    [0,5522]
worstHitChi2                  worstHitChi2                  worstHitChi2                  worstHitChi2                                                    'D'    [0.00271418760531,5.49989748001]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader1__def
#define IClassifierReader1__def

class IClassifierReader1 {

 public:

   // constructor
   IClassifierReader1() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader1() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP1 : public IClassifierReader1 {

 public:

   // constructor
   ReadMLP1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader1(),
        fClassName( "ReadMLP1" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "chi2", "nx", "ny", "X0Back", "worstHitChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.99922102689743;
      fVmax[0] = 0.852936625480652;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1.04708433151245;
      fVmin[4] = -0.998137891292572;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP1::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 17.476770401001;
   fWeightMatrix0to1[1][0] = 5.01611852645874;
   fWeightMatrix0to1[2][0] = -3.17710947990417;
   fWeightMatrix0to1[3][0] = 7.30337762832642;
   fWeightMatrix0to1[4][0] = -14.7253618240356;
   fWeightMatrix0to1[5][0] = -2.94592237472534;
   fWeightMatrix0to1[6][0] = -11.0142822265625;
   fWeightMatrix0to1[7][0] = 13.7013683319092;
   fWeightMatrix0to1[8][0] = -3.25789952278137;
   fWeightMatrix0to1[9][0] = 1.88936734199524;
   fWeightMatrix0to1[0][1] = -3.49101734161377;
   fWeightMatrix0to1[1][1] = -1.30894565582275;
   fWeightMatrix0to1[2][1] = 9.55676937103271;
   fWeightMatrix0to1[3][1] = -0.00229540513828397;
   fWeightMatrix0to1[4][1] = 2.8939049243927;
   fWeightMatrix0to1[5][1] = 0.651166260242462;
   fWeightMatrix0to1[6][1] = 0.930523753166199;
   fWeightMatrix0to1[7][1] = -2.61485242843628;
   fWeightMatrix0to1[8][1] = 8.25867176055908;
   fWeightMatrix0to1[9][1] = -14.0741739273071;
   fWeightMatrix0to1[0][2] = -2.66113185882568;
   fWeightMatrix0to1[1][2] = -1.23359477519989;
   fWeightMatrix0to1[2][2] = 1.59998691082001;
   fWeightMatrix0to1[3][2] = -10.6954469680786;
   fWeightMatrix0to1[4][2] = 3.52767205238342;
   fWeightMatrix0to1[5][2] = 0.427944749593735;
   fWeightMatrix0to1[6][2] = 3.8053412437439;
   fWeightMatrix0to1[7][2] = -1.81630456447601;
   fWeightMatrix0to1[8][2] = 9.47317600250244;
   fWeightMatrix0to1[9][2] = -6.7368860244751;
   fWeightMatrix0to1[0][3] = 5.43893051147461;
   fWeightMatrix0to1[1][3] = 2.23614621162415;
   fWeightMatrix0to1[2][3] = 1.70119047164917;
   fWeightMatrix0to1[3][3] = 8.82182025909424;
   fWeightMatrix0to1[4][3] = -1.95605516433716;
   fWeightMatrix0to1[5][3] = -37.0323867797852;
   fWeightMatrix0to1[6][3] = 0.0672433897852898;
   fWeightMatrix0to1[7][3] = 4.1481990814209;
   fWeightMatrix0to1[8][3] = -3.7395544052124;
   fWeightMatrix0to1[9][3] = 5.38001537322998;
   fWeightMatrix0to1[0][4] = 1.03683519363403;
   fWeightMatrix0to1[1][4] = -0.459750413894653;
   fWeightMatrix0to1[2][4] = -0.626950442790985;
   fWeightMatrix0to1[3][4] = -0.426535069942474;
   fWeightMatrix0to1[4][4] = 1.96699285507202;
   fWeightMatrix0to1[5][4] = 0.606670796871185;
   fWeightMatrix0to1[6][4] = 1.85718774795532;
   fWeightMatrix0to1[7][4] = -1.0095933675766;
   fWeightMatrix0to1[8][4] = -0.175936415791512;
   fWeightMatrix0to1[9][4] = 1.84664976596832;
   fWeightMatrix0to1[0][5] = 21.619176864624;
   fWeightMatrix0to1[1][5] = 4.42397308349609;
   fWeightMatrix0to1[2][5] = -11.4477739334106;
   fWeightMatrix0to1[3][5] = 14.5932893753052;
   fWeightMatrix0to1[4][5] = -17.2700214385986;
   fWeightMatrix0to1[5][5] = -37.4223289489746;
   fWeightMatrix0to1[6][5] = -9.36192893981934;
   fWeightMatrix0to1[7][5] = 13.9288845062256;
   fWeightMatrix0to1[8][5] = -16.9669628143311;
   fWeightMatrix0to1[9][5] = 15.3760366439819;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.695433139801025;
   fWeightMatrix1to2[0][1] = -1.00746583938599;
   fWeightMatrix1to2[0][2] = 0.414159774780273;
   fWeightMatrix1to2[0][3] = -0.565579950809479;
   fWeightMatrix1to2[0][4] = 1.28728699684143;
   fWeightMatrix1to2[0][5] = 0.709299325942993;
   fWeightMatrix1to2[0][6] = 0.471088141202927;
   fWeightMatrix1to2[0][7] = -0.721455156803131;
   fWeightMatrix1to2[0][8] = 0.583696067333221;
   fWeightMatrix1to2[0][9] = -0.706647396087646;
   fWeightMatrix1to2[0][10] = 3.0326817035675;
}

inline double ReadMLP1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP1::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP1::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP1::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP1::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00779165606946;
   fMax_1[0][0] = 37.0541687012;
   fMin_1[1][0] = 0.0658493563533;
   fMax_1[1][0] = 35.3492889404;
   fMin_1[2][0] = 0.00779165606946;
   fMax_1[2][0] = 37.0541687012;
   fMin_1[0][1] = 4;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 4;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 4;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 4;
   fMax_1[0][2] = 6;
   fMin_1[1][2] = 4;
   fMax_1[1][2] = 6;
   fMin_1[2][2] = 4;
   fMax_1[2][2] = 6;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 5522;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 5009;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 5522;
   fMin_1[0][4] = 0.00271418760531;
   fMax_1[0][4] = 5.49989748001;
   fMin_1[1][4] = 0.0164285302162;
   fMax_1[1][4] = 5.49989748001;
   fMin_1[2][4] = 0.00271418760531;
   fMax_1[2][4] = 5.49989748001;
}

//_______________________________________________________________________
inline void ReadMLP1::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP1::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP1::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
